name: pymicro
channels:
  - conda-forge
  - defaults
dependencies:
  # Needed to run pymicro and examples
  - python=3.8
  - numpy 
  - scipy>1.5.0
  - scikit-image 
  - pooch 
  - tifffile
  - matplotlib
  - vtk
  - h5py
  - lxml
  - pytables
  - basictools
  # Code quality
  - pylint
  - nose
  # Documentation
  - sphinx
  - sphinxcontrib-bibtex
  - nbsphinx
  - ipykernel 
  - pandoc 
