name: run-test

## run for all branches

on:
  push:
  workflow_dispatch:

jobs:
  test_and_doc:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package
        run: pip install .

      - name: Run tests
        run: |
          export PYTHONPATH=$PWD
          mkdir -p tesdata
          pytest --junitxml=tesdata/pymicro${{ matrix.python-version }}.xml

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: tesdata/pymicro${{ matrix.python-version }}.xml
